filter:
    excluded_paths: [tests/*, vendor/*]
before_commands:
    - composer install --dev --prefer-source
tools:
    php_cs_fixer:
        enabled: true
        config:
            level: all
    php_cpd:
        excluded_dirs: [vendor, tests]
    php_pdepend:
        excluded_dirs: [vendor, tests]
    php_analyzer: true
    php_code_coverage: true
